version: '3.8'
services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances-monitor
    environment:
      - GLANCES_OPT=-w -B 0.0.0.0
    ports:
      - "61208:61208"
    restart: unless-stopped
